/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 14-фев-2016 15:56:47 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `orders` CASCADE
;

DROP TABLE IF EXISTS `customers` CASCADE
;

DROP TABLE IF EXISTS `computers` CASCADE
;

DROP TABLE IF EXISTS `computer_vendors` CASCADE
;

DROP TABLE IF EXISTS `computer_types` CASCADE
;

DROP TABLE IF EXISTS `computer_providers` CASCADE
;

DROP TABLE IF EXISTS `components` CASCADE
;

/* Create Tables */

CREATE TABLE `orders`
(
	`orderkey` INTEGER NOT NULL AUTO_INCREMENT,
	`orderid` VARCHAR(50) 	 NULL,
	`customerid` INTEGER 	 NULL,
	`orderstartdate` DATETIME(0) 	 NULL,
	`ordercompletedate` DATETIME(0) 	 NULL,
	`computerid` INTEGER 	 NULL,
	`number` INTEGER 	 NULL,
	`amount` INTEGER 	 NULL,
	CONSTRAINT `PK_orders` PRIMARY KEY (`orderkey`)
)

;

CREATE TABLE `customers`
(
	`customerid` INTEGER NOT NULL AUTO_INCREMENT,
	`firstname` VARCHAR(50) 	 NULL,
	`secondname` VARCHAR(50) 	 NULL,
	`city` VARCHAR(50) 	 NULL,
	`address` VARCHAR(50) 	 NULL,
	`country` VARCHAR(50) 	 NULL,
	`phone` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_customers` PRIMARY KEY (`customerid`)
)

;

CREATE TABLE `computers`
(
	`computerid` INTEGER NOT NULL AUTO_INCREMENT,
	`typeid` INTEGER 	 NULL,
	`computername` VARCHAR(50) 	 NULL,
	`computerprice` INTEGER 	 NULL,
	`balance` INTEGER 	 NULL,
	`vendorid` CHAR(10) 	 NULL,
	`providerid` CHAR(10) 	 NULL,
	CONSTRAINT `PK_computers` PRIMARY KEY (`computerid`)
)

;

CREATE TABLE `computer_vendors`
(
	`vendorid` CHAR(10) NOT NULL,
	`vendorname` VARCHAR(50) 	 NULL,
	`vendoraddress` VARCHAR(50) 	 NULL,
	`vendorphone` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_vendors` PRIMARY KEY (`vendorid`)
)

;

CREATE TABLE `computer_types`
(
	`typeid` INTEGER NOT NULL AUTO_INCREMENT,
	`typename` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_types` PRIMARY KEY (`typeid`)
)

;

CREATE TABLE `computer_providers`
(
	`providerid` CHAR(10) NOT NULL,
	`providername` VARCHAR(50) 	 NULL,
	`provideraddress` VARCHAR(50) 	 NULL,
	`providerphone` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_computer_providers` PRIMARY KEY (`providerid`)
)

;

CREATE TABLE `components`
(
	`componentid` INTEGER NOT NULL AUTO_INCREMENT,
	`computerid` INTEGER 	 NULL,
	`componentname` VARCHAR(50) 	 NULL,
	`componentnum` INTEGER 	 NULL,
	CONSTRAINT `PK_components` PRIMARY KEY (`componentid`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `orders` 
 ADD INDEX `IXFK_orders_computers` (`computerid` ASC)
;

ALTER TABLE `orders` 
 ADD INDEX `IXFK_orders_customers` (`customerid` ASC)
;

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_providers` (`providerid` ASC)
;

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_types` (`typeid` ASC)
;

ALTER TABLE `computers` 
 ADD INDEX `IXFK_computers_computer_vendors` (`vendorid` ASC)
;

ALTER TABLE `components` 
 ADD INDEX `IXFK_components_computers` (`computerid` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `orders` 
 ADD CONSTRAINT `FK_orders_computers`
	FOREIGN KEY (`computerid`) REFERENCES `computers` (`computerid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `orders` 
 ADD CONSTRAINT `FK_orders_customers`
	FOREIGN KEY (`customerid`) REFERENCES `customers` (`customerid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_providers`
	FOREIGN KEY (`providerid`) REFERENCES `computer_providers` (`providerid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_types`
	FOREIGN KEY (`typeid`) REFERENCES `computer_types` (`typeid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_computer_vendors`
	FOREIGN KEY (`vendorid`) REFERENCES `computer_vendors` (`vendorid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `components` 
 ADD CONSTRAINT `FK_components_computers`
	FOREIGN KEY (`computerid`) REFERENCES `computers` (`computerid`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 ;
